### ISSUE TITLE
pypyodbc unable to load libodbc on macOS with Apple Silicon

### ISSUE THREAD

**Issue by sodul** [pypyodbc/pypyodbc#11]
On Apple Silicon homebew prefix is no longer `/usr/local` but `/opt/homebrew` this causes pypyodbc to fail:
```
> python -m pypyodbc
Traceback (most recent call last):
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pypyodbc.py", line 428, in <module>
    ODBC_API = ctypes.cdll.LoadLibrary('libodbc.so')
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libodbc.so, 0x0006): tried: 'libodbc.so' (no such file), '/usr/local/lib/libodbc.so' (no such file), '/usr/lib/libodbc.so' (no such file), '/Users/stephane/go/src/cdf/libodbc.so' (no such file), '/usr/local/lib/libodbc.so' (no such file), '/usr/lib/libodbc.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/stephane/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pypyodbc.py", line 440, in <module>
    raise OdbcNoLibrary('ODBC Library is not found. Is LD_LIBRARY_PATH set?')
__main__.OdbcNoLibrary: 'ODBC Library is not found. Is LD_LIBRARY_PATH set?'
```

Unfortunately `LD_LIBRARY_PATH` and other equivalent are no longer supported on macOS due to security concerns.

We use macOS 12, with homebrew (which installs some libraries used by python such as deadline and unixodbc), and python 3.10.2 installed trough pyenv.

We tried to add `LDFLAGS="-L$(brew --prefix)/lib` when calling pyenv to build python with no success.

**Comment by sodul** [comment]
@rolweber can you do a release with the fix? We are still applying the a patch file on our side since the most recent release is still from 2021 and predates the fix.

Thank you!

**Comment by rolweber** [comment]
Sorry, the main branch is not fit for release. We'd have to backport the fix to the 1.3.x branch. And there's no release automation for that branch, my pending PR is for `main` only. Given my current workload, I don't see a new release happening anytime soon.
